### ISSUE TITLE
Handling of null values

### ISSUE THREAD

**Issue by chr1st1ank** [angelnu/thethingsnetwork_python_client#5]
First of all, let me thank you for taking the initiative and writing a new home assistant integration for TTN. This is really awesome and I've been looking forward to it!

Now that it became available in Home Assistant I directly tried it out and ran into an issue with handling of not existing values. This is the stacktrace:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/thethingsnetwork/coordinator.py", line 51, in _async_update_data
    measurements = await self._client.fetch_data()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ttn_client/client.py", line 139, in fetch_data
    return await self.__storage_api_call(f"?last={fetch_last}&order=received_at")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ttn_client/client.py", line 193, in __storage_api_call
    TTNClient.__add_value(
  File "/usr/local/lib/python3.12/site-packages/ttn_client/client.py", line 238, in __add_value
    raise TypeError(f"Unexpected type {type(new_value)} for value: {new_value}")
TypeError: Unexpected type <class 'NoneType'> for value: None
```

I ran this library's code in debug mode and could reproduce the very same with the following "test" function:
```python

def test_fetch_data():
    """Try to fetch data."""
    client = ttn_client.TTNClient(
        hostname="eu1.cloud.thethings.network",
        application_id="<my-app-id>",
        access_key="<super-secret-key>",
    )
    assert client is not None
    data = asyncio.run(client.fetch_data())
```

This why I could find out that `uplink_message["decoded_payload"]` in this line https://github.com/angelnu/thethingsnetwork_python_client/blob/0ce36cd7e32af82cf33674092ef72b43a63b2493/src/ttn_client/client.py#L192 has the following content when it crashes:
```
{
        "BLE_MD": 0,
        "BatV": 2.84,
        "FIRMWARE_VERSION": "1.4.1",
        "FREQUENCY_BAND": "EU868",
        "GPS_M0D": 1,
        "Intwk": 0,
        "LON": "ON",
        "PNACKMD": None,
        "SENSOR_MODEL": "TrackerD",
        "SMODE": "GPS",
        "SUB_BAND": "NULL",
    }
```

The problem is caused by the `None` value of `PNACKMD`, a type not handled here: https://github.com/angelnu/thethingsnetwork_python_client/blob/0ce36cd7e32af82cf33674092ef72b43a63b2493/src/ttn_client/client.py#L238

I would write a PR to just skip none values, if that finds your appreciation.

**Comment by chr1st1ank** [comment]
I think the payload formatter of my device (https://github.com/dragino/dragino-end-node-decoder/blob/main/TrackerD/TrackerD%20TTN%20Decoder%201.4.9.txt) is buggy in the sense that it always sets the value PNACKMD to Null if I see it right.

But that shouldn't be a reason for the client to entirely crash.

**Comment by angelnu** [comment]
Agreed - it should try to take as much as possible and just warn on the rest not being well formated. This should motivate for well behaving formaters while allowing to mute the warning while waiting for a fix.

Keeping open until we have a warning.
